from shared.schemas import (
    EtudiantCreate,
    EtudiantGroupeOut,
    EtudiantOut,
    EtudiantSearchResponse,
    EtudiantUpdate,
    GroupeCreate,
    GroupeOut,
    GroupeUpdate,
    PromotionCreate,
    PromotionOut,
    PromotionUpdate,
    RoleAssignmentCreate,
    UtilisateurRoleOut,
)

__all__ = [
    "EtudiantCreate",
    "EtudiantGroupeOut",
    "EtudiantOut",
    "EtudiantSearchResponse",
    "EtudiantUpdate",
    "GroupeCreate",
    "GroupeOut",
    "GroupeUpdate",
    "PromotionCreate",
    "PromotionOut",
    "PromotionUpdate",
    "RoleAssignmentCreate",
    "UtilisateurRoleOut",
]
